[build]
  # No build command needed for static site
  publish = "."

[build.environment]
  # Environment variables if needed

[[headers]]
  # Apply security headers to all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  # Cache static assets
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/svg/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/webfonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"